{'total_transactions': 5,
 'transactions': [
            {'account_owner': None,
             'date': '2020-06-08',
             'amount': 1200,
             'transaction_code': None,
             'category_id': '21012001', 
             'name': 'CHECK #552', 
             'transaction_type': 'special', 
             'iso_currency_code': 'USD', 
             'account_id': 'pgXypevDNxT8NXboNvVnF0wv9oX5LJUJRoaYg', 
             'payment_meta': {'reference_number': None, 
                                'ppd_id': None, 
                                'payee': None, 
                                'payment_method': None, 
                                'by_order_of': None, 
                                'payment_processor': None, 
                                'reason': None, 
                                'payer': None}, 
            'unofficial_currency_code': None, 
            'payment_channel': 'other', 
            'pending_transaction_id': None, 
            'authorized_date': None, 
            'pending': False, 
            'transaction_id': '4dgm6yRJ5nIr6d5X6Z4VTv7OpYD3a9Hkx9q3E', 
            'location': {'postal_code': None, 
                             'lon': None, 
                             'country': None, 
                             'address': None, 
                             'region': None, 
                             'lat': None, 
                             'store_number': None, 
                             'city': None}, 
            'category': ['Transfer', 'Withdrawal', 'Check']}, 
            {'account_owner': None, 'date': '2020-06-02', 'amount': -2010, 'transaction_code': None, 'category_id': '21005000', 'name': 'BANK OF AMERICA', 'transaction_type': 'special', 'iso_currency_code': 'USD', 'account_id': 'pgXypevDNxT8NXboNvVnF0wv9oX5LJUJRoaYg', 'payment_meta': {'reference_number': None, 'ppd_id': None, 'payee': None, 'payment_method': None, 'by_order_of': None, 'payment_processor': None, 'reason': None, 'payer': None}, 'unofficial_currency_code': None, 'payment_channel': 'other', 'pending_transaction_id': None, 'authorized_date': None, 'pending': False, 'transaction_id': 'akQ9RpNnqdTbOE1gOVe3uLrD60yE51HZxB464', 'location': {'postal_code': None, 'lon': None, 'country': None, 'address': None, 'region': None, 'lat': None, 'store_number': None, 'city': None}, 'category': ['Transfer', 'Credit']}, 
            {'account_owner': None, 'date': '2020-05-29', 'amount': -0.21, 'transaction_code': None, 'category_id': '15001000', 'name': 'INTEREST CREDIT', 'transaction_type': 'special', 'iso_currency_code': 'USD', 'account_id': 'noqBpek6KAS4X97ZXk5jc4YkzZxwaAfAKZ7zw', 'payment_meta': {'reference_number': None, 'ppd_id': None, 'payee': None, 'payment_method': None, 'by_order_of': None, 'payment_processor': None, 'reason': None, 'payer': None}, 'unofficial_currency_code': None, 'payment_channel': 'other', 'pending_transaction_id': None, 'authorized_date': None, 'pending': False, 'transaction_id': 'r9BkpejP0rs3PebRPjgkInLM79A0vEHBNRbXK', 'location': {'postal_code': None, 'lon': None, 'country': None, 'address': None, 'region': None, 'lat': None, 'store_number': None, 'city': None}, 'category': ['Interest', 'Interest Earned']}, 
            {'account_owner': None, 'date': '2020-05-26', 'amount': -2010, 'transaction_code': None, 'category_id': '21005000', 'name': 'BANK OF AMERICA', 'transaction_type': 'special', 'iso_currency_code': 'USD', 'account_id': 'pgXypevDNxT8NXboNvVnF0wv9oX5LJUJRoaYg', 'payment_meta': {'reference_number': None, 'ppd_id': None, 'payee': None, 'payment_method': None, 'by_order_of': None, 'payment_processor': None, 'reason': None, 'payer': None}, 'unofficial_currency_code': None, 'payment_channel': 'other', 'pending_transaction_id': None, 'authorized_date': None, 'pending': False, 'transaction_id': 'x6Z4Xe8kNrUgnzePn8X6HZ3856da1EFMqXody', 'location': {'postal_code': None, 'lon': None, 'country': None, 'address': None, 'region': None, 'lat': None, 'store_number': None, 'city': None}, 'category': ['Transfer', 'Credit']}, 
            {'account_owner': None, 'date': '2020-05-19', 'amount': 1004.04, 'transaction_code': None, 'category_id': '16001000', 'name': 'CHASE CREDIT CRD', 'transaction_type': 'special', 'iso_currency_code': 'USD', 'account_id': 'pgXypevDNxT8NXboNvVnF0wv9oX5LJUJRoaYg', 'payment_meta': {'reference_number': None, 'ppd_id': None, 'payee': None, 'payment_method': None, 'by_order_of': None, 'payment_processor': None, 'reason': None, 'payer': None}, 'unofficial_currency_code': None, 'payment_channel': 'other', 'pending_transaction_id': None, 'authorized_date': None, 'pending': False, 'transaction_id': 'J8ZPRVjr51FgYe1AYDwRHBAypOedbDCbPdkyv', 'location': {'postal_code': None, 'lon': None, 'country': None, 'address': None, 'region': None, 'lat': None, 'store_number': None, 'city': None}, 'category': ['Payment', 'Credit Card']}], 
 'request_id': '8tsVktinDxUmF2w', 
 'accounts': [{'balances': {'iso_currency_code': 'USD', 'limit': None, 'available': 25580.85, 'unofficial_currency_code': None, 'current': 25580.85}, 
                   'official_name': 'CHECKING', 'type': 'depository', 'account_id': 'pgXypevDNxT8NXboNvVnF0wv9oX5LJUJRoaYg', 'subtype': 'checking', 'mask': '0174', 'name': 'CHECKING'}, 
              {'balances': {'iso_currency_code': 'USD', 'limit': None, 'available': 13216.97, 'unofficial_currency_code': None, 'current': 13216.97}, 
                    'official_name': 'SAVINGS', 'type': 'depository', 'account_id': 'noqBpek6KAS4X97ZXk5jc4YkzZxwaAfAKZ7zw', 'subtype': 'savings', 'mask': '2219', 'name': 'SAVINGS'}], 
 'item': {'billed_products': ['transactions'], 
          'institution_id': 'ins_113873', 
          'webhook': '', 
          'item_id': 'akQ9RpNnqdTbOE1gOVe3uLE0Aywm40tZoB56j', 
          'available_products': ['auth', 'balance'], 
          'consent_expiration_time': None, 'error': None}}